/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#8fa8c2",
        "surface-bright": "#255d9e",
        "tertiary-container": "#dae3ef",
        "on-tertiary-container": "#5c656f",
        secondary: "#c6c6c7",
        "surface-variant": "#205295",
        "surface-container-low": "#0e355c",
        outline: "#2C74B3",
        primary: "#ffffff",
        "error-container": "#93000a",
        tertiary: "#ffffff",
        background: "#0A2647",
        "surface-card": "#144272",
        "on-tertiary-fixed-variant": "#3f4851",
        "on-error": "#690005",
        "on-secondary": "#2f3131",
        "surface-tint": "#2C74B3",
        "primary-fixed": "#2C74B3",
        "on-primary": "#FFFFFF",
        "on-background": "#E2EEF9",
        "on-tertiary-fixed": "#141c25",
        "surface-container-highest": "#205295",
        "on-secondary-fixed-variant": "#454747",
        "on-secondary-container": "#b4b5b5",
        surface: "#0C2D52",
        "inverse-on-surface": "#303124",
        "on-error-container": "#ffdad6",
        "surface-dim": "#0A2647",
        error: "#ffb4ab",
        "on-primary-fixed": "#FFFFFF",
        "outline-variant": "#1d3d63",
        "on-primary-fixed-variant": "#434b00",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "primary-container": "#2C74B3",
        "secondary-container": "#454747",
        "surface-container-high": "#1d538c",
        "surface-container": "#144272",
        "on-primary-container": "#FFFFFF",
        "primary-fixed-dim": "#276aa5",
        "on-tertiary": "#28313a",
        "inverse-primary": "#596400",
        "inverse-surface": "#e4e4d0",
        "tertiary-fixed": "#dae3ef",
        "surface-container-lowest": "#08213f",
        "on-surface": "#E2EEF9",
        "tertiary-fixed-dim": "#bec7d3",
        "on-secondary-fixed": "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "stack-lg": "40px",
        "stack-md": "16px",
        gutter: "24px",
        "card-gap": "32px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "section-padding-v": "100px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg-mobile": ["Syne", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        button: ["DM Sans", "sans-serif"],
        "label-mono": ["Space Mono", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["84px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "400" }],
      },
      keyframes: {
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
