/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#6B7280",
        "surface-bright": "#FFFFFF",
        "tertiary-container": "#E4EAF7",
        "on-tertiary-container": "#374151",
        secondary: "#6B7280",
        "surface-variant": "#E4EAF7",
        "surface-container-low": "#EDF1FB",
        outline: "#C7D0E4",
        primary: "#1F2937",
        "error-container": "#93000a",
        tertiary: "#1F2937",
        background: "#F5F7FF",
        "surface-card": "#FFFFFF",
        "on-tertiary-fixed-variant": "#4B5563",
        "on-error": "#690005",
        "on-secondary": "#FFFFFF",
        "surface-tint": "#2563EB",
        "primary-fixed": "#2563EB",
        "on-primary": "#FFFFFF",
        "on-background": "#374151",
        "on-tertiary-fixed": "#1F2937",
        "surface-container-highest": "#D5DCEC",
        "on-secondary-fixed-variant": "#4B5563",
        "on-secondary-container": "#374151",
        surface: "#FFFFFF",
        "inverse-on-surface": "#F5F7FF",
        "on-error-container": "#ffdad6",
        "surface-dim": "#EDF1FB",
        error: "#ffb4ab",
        "on-primary-fixed": "#FFFFFF",
        "outline-variant": "#D5DCEC",
        "on-primary-fixed-variant": "#1D4ED8",
        "secondary-fixed": "#E4EAF7",
        "secondary-fixed-dim": "#D5DCEC",
        "primary-container": "#DBE6FE",
        "secondary-container": "#E4EAF7",
        "surface-container-high": "#D5DCEC",
        "surface-container": "#EDF1FB",
        "on-primary-container": "#1E3A8A",
        "primary-fixed-dim": "#3B76F0",
        "on-tertiary": "#1F2937",
        "inverse-primary": "#2563EB",
        "inverse-surface": "#1F2937",
        "tertiary-fixed": "#E4EAF7",
        "surface-container-lowest": "#FFFFFF",
        "on-surface": "#1F2937",
        "tertiary-fixed-dim": "#D5DCEC",
        "on-secondary-fixed": "#1F2937",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "stack-lg": "40px",
        "stack-md": "16px",
        gutter: "24px",
        "card-gap": "32px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "section-padding-v": "100px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg-mobile": ["Syne", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        button: ["DM Sans", "sans-serif"],
        "label-mono": ["Space Mono", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["84px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "400" }],
      },
      keyframes: {
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
